# Generated by Django 5.2 on 2025-05-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_url_options_url_custom_code_url_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickanalytics',
            name='domain_used',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
