# Generated by Django 5.2 on 2025-05-31 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_clickanalytics_domain_used_url_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_malware_scanning', models.BooleanField(default=True)),
                ('enable_rate_limiting', models.BooleanField(default=True)),
                ('enable_captcha', models.BooleanField(default=True)),
                ('max_urls_per_hour', models.IntegerField(default=50)),
                ('max_urls_per_day', models.IntegerField(default=500)),
                ('suspicious_click_threshold', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name_plural': 'Security Settings',
            },
        ),
        migrations.RemoveField(
            model_name='url',
            name='password',
        ),
        migrations.AddField(
            model_name='url',
            name='block_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='url',
            name='flagged_by_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='url',
            name='is_safe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='url',
            name='last_security_scan',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='security_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='url',
            name='temporarily_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='url',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BlockedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('blocked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LinkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_ip', models.GenericIPAddressField()),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('report_type', models.CharField(choices=[('malware', 'Malware'), ('phishing', 'Phishing'), ('spam', 'Spam'), ('inappropriate', 'Inappropriate Content'), ('scam', 'Scam'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('investigated', models.BooleanField(default=False)),
                ('action_taken', models.CharField(blank=True, max_length=200)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='shortener.url')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('malware', 'Malware Scan'), ('phishing', 'Phishing Scan'), ('reputation', 'Reputation Check')], max_length=20)),
                ('result', models.CharField(choices=[('safe', 'Safe'), ('suspicious', 'Suspicious'), ('malicious', 'Malicious'), ('error', 'Scan Error')], max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('scanner_service', models.CharField(default='internal', max_length=100)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_scans', to='shortener.url')),
            ],
        ),
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('activity_type', models.CharField(choices=[('rapid_creation', 'Rapid URL Creation'), ('suspicious_pattern', 'Suspicious Pattern'), ('malicious_url', 'Malicious URL Attempt'), ('bot_behavior', 'Bot-like Behavior'), ('captcha_failure', 'Repeated Captcha Failures')], max_length=30)),
                ('description', models.TextField()),
                ('severity', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('metadata', models.JSONField(default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhitelistedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RateLimitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('blocked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address', 'timestamp'], name='shortener_r_ip_addr_f7a761_idx'), models.Index(fields=['user', 'timestamp'], name='shortener_r_user_id_8e57fe_idx')],
            },
        ),
    ]
