# Generated by Django 5.2 on 2025-06-02 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_securitysettings_remove_url_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='expiry_date',
        ),
    ]
